services:
  db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: program
      POSTGRES_DB: program
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - program_pg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U program -d program"]
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  program_pg:
